"""
Generated by AI: add traits JSONField to StudentPerformance
"""
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_studentperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='traits',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]

